# config.yml

paths:
  # Adjust this to your project root dir
  root_directory: "/home/ali/tum/motion_planning/social_ai_practical_course"

data:
  raw_data_path_ind: "data/raw/inD/data/"
  processed_data_path_ind: 'data/processed/inD/'
  number_of_recordings: 32


  processed_data_path_ind_test_set:
    processed_data_test_set_0: "data/processed/inD/x_y_recording_00_range_384.csv"
    processed_data_dif_set: 'data/processed/scenario_samples/lane_merging/dif_set/test_set_00.csv'
 
  recording: "00"
  n: 384

  raw_data_path_exid:
    exid_00: 'data/raw/exiD/data/00_tracks.csv'

 
directories:
  root_directory: "/home/ali/tum/motion_planning/social_ai_practical_course"

models:
  model_save_path: "results/models/"

# Visulsation of predicted cars
visualisation:
  # Define base paths
  base_raw_path: 'data/raw/inD/data/'
  base_processed_path: 'data/processed/visualization_data/'
  tracks_number:          '00_tracks.csv'
  tracks_meta_number:     '00_tracksMeta.csv'
  recording_meat_number:  '00_recordingMeta.csv'
  background_number:      '00_background.png'
  # Specify car ids that you want to visualize
  track_ids:
    - 1
    - 2

figures:
  show_and_save_figures: True
  # show_and_save_figures: False    # Uncomment this if you dont want to show and save the figures
  figures_save_path: "results/figures/"
